/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EzInput {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLEzInputElement extends Components.EzInput, HTMLStencilElement {
    }
    var HTMLEzInputElement: {
        prototype: HTMLEzInputElement;
        new (): HTMLEzInputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ez-input": HTMLEzInputElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface EzInput {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "ez-input": EzInput;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ez-input": LocalJSX.EzInput & JSXBase.HTMLAttributes<HTMLEzInputElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
