/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EvilPhonenumberInput {
        "debug"?: boolean;
    }
    interface EzInput {
    }
    interface FooBar {
    }
    interface MyComponent {
    }
    interface NumberDropdownInput {
        "itemNumber": number;
        "itemPrefix": string;
        "value": string;
    }
    interface SizeableWindow {
        "windowTitle": string;
    }
}
export interface EvilPhonenumberInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEvilPhonenumberInputElement;
}
export interface NumberDropdownInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNumberDropdownInputElement;
}
declare global {
    interface HTMLEvilPhonenumberInputElement extends Components.EvilPhonenumberInput, HTMLStencilElement {
    }
    var HTMLEvilPhonenumberInputElement: {
        prototype: HTMLEvilPhonenumberInputElement;
        new (): HTMLEvilPhonenumberInputElement;
    };
    interface HTMLEzInputElement extends Components.EzInput, HTMLStencilElement {
    }
    var HTMLEzInputElement: {
        prototype: HTMLEzInputElement;
        new (): HTMLEzInputElement;
    };
    interface HTMLFooBarElement extends Components.FooBar, HTMLStencilElement {
    }
    var HTMLFooBarElement: {
        prototype: HTMLFooBarElement;
        new (): HTMLFooBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNumberDropdownInputElement extends Components.NumberDropdownInput, HTMLStencilElement {
    }
    var HTMLNumberDropdownInputElement: {
        prototype: HTMLNumberDropdownInputElement;
        new (): HTMLNumberDropdownInputElement;
    };
    interface HTMLSizeableWindowElement extends Components.SizeableWindow, HTMLStencilElement {
    }
    var HTMLSizeableWindowElement: {
        prototype: HTMLSizeableWindowElement;
        new (): HTMLSizeableWindowElement;
    };
    interface HTMLElementTagNameMap {
        "evil-phonenumber-input": HTMLEvilPhonenumberInputElement;
        "ez-input": HTMLEzInputElement;
        "foo-bar": HTMLFooBarElement;
        "my-component": HTMLMyComponentElement;
        "number-dropdown-input": HTMLNumberDropdownInputElement;
        "sizeable-window": HTMLSizeableWindowElement;
    }
}
declare namespace LocalJSX {
    interface EvilPhonenumberInput {
        "debug"?: boolean;
        "onChange"?: (event: EvilPhonenumberInputCustomEvent<string>) => void;
    }
    interface EzInput {
    }
    interface FooBar {
    }
    interface MyComponent {
    }
    interface NumberDropdownInput {
        "itemNumber"?: number;
        "itemPrefix"?: string;
        "onChange"?: (event: NumberDropdownInputCustomEvent<string>) => void;
        "value"?: string;
    }
    interface SizeableWindow {
        "windowTitle"?: string;
    }
    interface IntrinsicElements {
        "evil-phonenumber-input": EvilPhonenumberInput;
        "ez-input": EzInput;
        "foo-bar": FooBar;
        "my-component": MyComponent;
        "number-dropdown-input": NumberDropdownInput;
        "sizeable-window": SizeableWindow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "evil-phonenumber-input": LocalJSX.EvilPhonenumberInput & JSXBase.HTMLAttributes<HTMLEvilPhonenumberInputElement>;
            "ez-input": LocalJSX.EzInput & JSXBase.HTMLAttributes<HTMLEzInputElement>;
            "foo-bar": LocalJSX.FooBar & JSXBase.HTMLAttributes<HTMLFooBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "number-dropdown-input": LocalJSX.NumberDropdownInput & JSXBase.HTMLAttributes<HTMLNumberDropdownInputElement>;
            "sizeable-window": LocalJSX.SizeableWindow & JSXBase.HTMLAttributes<HTMLSizeableWindowElement>;
        }
    }
}
